test_news/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]  

test_news/test_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import re_path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from news.view import NewsView, oneNewView
from .view import redirect_view


urlpatterns = [
    # создание, получение новостей
    # отдельной новости
    path('news/<int:pk>/', oneNewView.as_view(), name = 'OneNew'),
    path('news/', NewsView.as_view(), name = 'News'),
    path('',  NewsView.as_view(), name = 'News'),


    # роутинг авторизации
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    ]
                      

test_news/accounts/models.py
from django.db import models

# Create your models here.

test_news/commentary/models.py
from django.conf import settings
from django.db import models
from news.models import News
from mptt.models import MPTTModel, TreeForeignKey
class Comments(MPTTModel): # Таблица комментариев которая наследует models.Model
    
    # текст комментария
    comment_text = models.TextField() # Текст комментария
    
    # родительский комментарий
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    # связь с новостью
    new = models.ForeignKey(News, on_delete=models.CASCADE, null =True)

    # автор комментария
    comment_autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank = True, null = True)

    
    class Meta:
        verbose_name = ("Category") # человекочитаемое имя объекта
        verbose_name_plural = ("Categories")  #человекочитаемое множественное имя для Комментариев
    def __str__(self):
        return self.comment_text  # __str__ применяется для отображения объекта в интерфейсе

    class MPTTMeta:
         order_insertion_by = ['comment_text']

test_news/comments/models.py
from django.db import models
from news.models import News
class Comments(models.Model): # Таблица комментариев которая наследует models.Model
    
    # текст комментария
    comment_text = models.TextField() # Текст комментария
    
    # родительский комментарий
    parent = models.ForeignKey('self',models.SET_NULL, unique=False, blank=True, null=True)
    
    # связь с новостью
    new = models.ForeignKey(News, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = ("Category") # человекочитаемое имя объекта
        verbose_name_plural = ("Categories")  #человекочитаемое множественное имя для Комментариев
    def __str__(self):
        return self.comment_text  # __str__ применяется для отображения объекта в интерфейсе

test_news/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.
class News(models.Model): # Таблица новостей которая наследует models.Model
    name = models.CharField(max_length=100) # название новости
    new_text = models.TextField(blank=False) # текст новости 
    date_of_create = models.DateField(auto_now_add=True) # дата создания
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank = True, null = True)

    class Meta:
        verbose_name = ("New") # человекочитаемое имя объекта
        verbose_name_plural = ("News")  #человекочитаемое множественное имя для Новостей
    def __str__(self):
        return self.name  # __str__ применяется для отображения объекта в интерфейсе

test_news/accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html' 

test_news/commentary/views.py
from django.shortcuts import render

# Create your views here.

test_news/templates/base.html
<!DOCTYPE html>
<head>
  <title> Новостное приложение </title>
</head>
<body>
        	<div class="navbar-start">

			{% if user.is_authenticated %}
  				Hi {{ user.username }}!
  				<a href="{% url 'logout' %}">Log Out</a></p>
			{% else %}
  				<p>You are not logged in
				<a href="{% url 'signup' %}">Sign Up</a>
				or  
				<a href="{% url 'login' %}">Log In</a><p>

			{% endif %}
			
			<a class="navbar-item" href="/news"> Новости </a><p>
						
        	</div>
         </div>
	</nav>
<!-- в блок контент мы будем подгружать наши странички -->
{% block content %}


{% endblock %}
</div>
</body>
</html>

test_news/templates/news/get.html
{% extends 'base.html' %}
{% block content %}

<!-- Форма создания новой новости -->
<form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit"> Создать новость </button>
</form>


<ul>

<!-- Все новости -->

    {% for new in news %}
<b>	<a class="navbar-item" href="/news/{{new.id}}"> {{ new.name }} <a></b> <br>
   {{ new.new_text}}<br>
   {{ new.date_of_create}}<br>
   {{ new.autor}}<br>
    
    ------------------------------<p>
{% endfor %}
    </ul>

{% endblock %}

test_news/templates/news/get1.html
{% extends 'base.html' %}
{% block content %}


<b>{{ new.name }}</b> <br>
   {{ new.new_text}}<br>
   {{ new.date_of_create}}<br>
   {{ new.autor}}<br><br>

<!-- Дерево комментариев
    в работе библиотека mptt -->
{% load mptt_tags %}
<ul>
    
    {% recursetree comments %}
        
        <li>
            <!-- Создаем список из деревьев
                **магия mptt** -->
            {{ node.comment_text }}
            
            <font color="gray">
            [{{node.comment_autor}}]
            </font>
            <!-- Кнопка с классом btn -->
            <button class="btn" id="btn--{{node.id}}" type="button">
                Ответить
            </button>

            <!-- Класс скрытой формы, которая открывается
                 при нажатие на кнопку Ответить class = btn -->
            <div class="content" id="content--{{node.id}}">
            
            <b>Ответ на комментарий:</b> <br>
            <i>{{node}}</i>
                
                <form  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ comment_form.comment_text }}
                    <!-- Два дополнительных скрытых поля, которые берутся 
                        из комментария на который дает ответ -->
                    <input id="id_new" type="hidden" name="new" value={{new.id}} /></p>
                    <input id="id_parent" type="hidden" name="parent" value={{node.id}} /></p>
                
                    <button type="submit"> Отправить </button>
                 </form>
            
            </div>

            <style type="text/css">
                  
                  .content {
                    display: none;
                  }

                  .content--visible {
                      display: block;
                  }
                                    
            </style>
          
            
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                    
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}

    <!-- Скрипт управления кнопкой -->
    <script>
        const buttons = document.querySelectorAll(".btn")
        
        console.log(buttons);
        
        buttons.forEach((button) => button.addEventListener("click", btnClick));

        function btnClick(e) {
            console.log(e.target.id);
            
            const buttonId = e.target.id.split("--")[1]
            const content = document.querySelector(`#content--${buttonId}`)
            content.classList.toggle("content--visible")
            
            console.log(content);
            
        }
    </script>
</ul>
   
<!-- Создать комментарий к статье, 
    не к другому комментарию   -->

   <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ comment_form.comment_text }}


    <input id="id_new" type="hidden" name="new" value={{new.id}} /></p>
    <button type="submit"> Комментарий </button>
 </form>

{% endblock %}